### ISSUE TITLE
General Writing feedback

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/phase-3-python-loops#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195246?module_item_id=439014

### Concern

**1.** In the first sentence of the **Basic Loops in Python** section, our sentence reads `In JavaScript, there are a few common approaches to for control flow that will allow us to run the same lines of code over and over again.` Having both `to` and `for` in between `approaches` and `control` is grammatically incorrect. Either would probably work fine on its own.

**2.** When discussing ranges, we neglect to mention that the number passed to the range (or the second number passed, if we give it a starting and ending point) isn't included in the range. We also don't discuss the fact that you can give a range a starting and ending point - we just tell students that ranges start at 0.

**Comment by professor-ben** [comment]
Good catch! Will push up the fix in a moment.
